import {
  House,
  Search,
  MapPinned,
} from "lucide-react";

export const currentUser = {
  name: "Dawson Ash",
  username: "@dawsonash",
  year: "Junior",
  major: "Computer Science",
  homeBase: "Boulder / The Hill",
  studentVerified: true,
  hostRating: 4.8,
  guestRating: 4.9,
  friends: 126,
  eventsHosted: 11,
  eventsAttended: 34,
  bio: "Community-first student who loves themed events, meeting new people, and helping friends find the right vibe.",
  interests: [
    "Kickbacks",
    "Live Music",
    "Game Night",
    "Tailgates",
    "House Shows",
  ],
};

export const events = [
  {
    id: 1,
    title: "Flatiron Rooftop Kickback",
    type: "Kickback",
    dateLabel: "Thursday, March 13",
    isTonight: true,
    dateValue: "2026-03-13",
    location: "The Hill",
    area: "2 min from campus",
    fee: 5,
    visibility: "Public",
    theme: "Late Night Social",
    friendsGoing: 8,
    capacityCurrent: 42,
    capacityTotal: 60,
    host: "Maya R.",
    hostRating: 4.9,
    tags: ["Relaxed", "Friends Going", "Verified Host"],
    image:
      "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=1200&q=80",
    mutuals: ["Sofia", "Jordan", "Nina"],
    status: "RSVP Open",
  },
  {
    id: 2,
    title: "Basement Beats: Y2K Theme Night",
    type: "House Party",
    dateLabel: "Friday, March 14",
    isTonight: false,
    dateValue: "2026-03-14",
    location: "South Boulder",
    area: "Address after approval",
    fee: 10,
    visibility: "Friends + Invite Requests",
    theme: "Y2K",
    friendsGoing: 14,
    capacityCurrent: 88,
    capacityTotal: 100,
    host: "Ethan K.",
    hostRating: 4.7,
    tags: ["High Energy", "Theme", "Approval Required"],
    image:
      "https://images.unsplash.com/photo-1496024840928-4c417adf211d?auto=format&fit=crop&w=1200&q=80",
    mutuals: ["Cam", "Alex", "Riley"],
    status: "Request Invite",
  },
  {
    id: 3,
    title: "Pearl Street House Show Afterparty",
    type: "Afterparty",
    dateLabel: "Saturday, March 15",
    isTonight: false,
    dateValue: "2026-03-15",
    location: "Downtown Boulder",
    area: "Pearl Street",
    fee: 0,
    visibility: "Public",
    theme: "Live Music Crowd",
    friendsGoing: 5,
    capacityCurrent: 25,
    capacityTotal: 40,
    host: "Jordan T.",
    hostRating: 4.8,
    tags: ["Music", "Smaller Crowd", "Trusted Guests"],
    image:
      "https://images.unsplash.com/photo-1501386761578-eac5c94b800a?auto=format&fit=crop&w=1200&q=80",
    mutuals: ["Owen", "Grace"],
    status: "RSVP Open",
  },
  {
    id: 4,
    title: "Buffs Post-Game Social",
    type: "Social",
    dateLabel: "Sunday, March 16",
    isTonight: false,
    dateValue: "2026-03-16",
    location: "Near Folsom",
    area: "Approximate pin only",
    fee: 3,
    visibility: "Public",
    theme: "Game Day",
    friendsGoing: 19,
    capacityCurrent: 71,
    capacityTotal: 90,
    host: "Sofia L.",
    hostRating: 4.9,
    tags: ["Campus", "Welcoming", "Low Pressure"],
    image:
      "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=1200&q=80",
    mutuals: ["Noah", "Mila", "Sage"],
    status: "RSVP Open",
  },
  {
    id: 5,
    title: "Late Night Apartment Mixer",
    type: "Mixer",
    dateLabel: "Saturday, March 15",
    isTonight: false,
    dateValue: "2026-03-15",
    location: "North Boulder",
    area: "Address after RSVP",
    fee: 2,
    visibility: "Public",
    theme: "Casual",
    friendsGoing: 11,
    capacityCurrent: 36,
    capacityTotal: 50,
    host: "Chris D.",
    hostRating: 4.6,
    tags: ["Casual", "Apartment", "Friends Going"],
    image:
      "https://images.unsplash.com/photo-1517457373958-b7bdd4587205?auto=format&fit=crop&w=1200&q=80",
    mutuals: ["Ben", "Lucy"],
    status: "RSVP Open",
  },
  {
    id: 6,
    title: "Sunday Reset Social",
    type: "Social",
    dateLabel: "Sunday, March 16",
    isTonight: false,
    dateValue: "2026-03-16",
    location: "Central Boulder",
    area: "Approximate pin only",
    fee: 0,
    visibility: "Public",
    theme: "Chill",
    friendsGoing: 7,
    capacityCurrent: 22,
    capacityTotal: 35,
    host: "Ava P.",
    hostRating: 4.8,
    tags: ["Free", "Low Pressure", "Welcoming"],
    image:
      "https://images.unsplash.com/photo-1528605248644-14dd04022da1?auto=format&fit=crop&w=1200&q=80",
    mutuals: ["Emma", "Sam"],
    status: "RSVP Open",
  },
];

export const navItems = [
  { id: "home", label: "Home", icon: House },
  { id: "search", label: "Search", icon: Search },
  { id: "map", label: "Map", icon: MapPinned },
];

export const filters = [
  "All",
  "Tonight",
  "This Weekend",
  "Friends Going",
  "Public",
  "Free",
];

export const searchLocations = [
  "All Locations",
  "The Hill",
  "South Boulder",
  "Downtown Boulder",
  "North Boulder",
  "Central Boulder",
  "Near Folsom",
];

export const searchVisibility = ["Any Access", "Public", "Friends + Invite Requests"];

export const searchTypes = [
  "All Types",
  "Kickback",
  "House Party",
  "Afterparty",
  "Social",
  "Mixer",
];
